### ISSUE TITLE
 socket.error: [Errno 111] Connection refused

### ISSUE THREAD

**Issue by julian70400** [jarus/munin-prosody#14]
Hello,
 
On a fresh install  munin-node v2.0.49 & Prosody 0.11.2 : 

```
2020/11/19-15:55:03 [25606] Error output from prosody_s2s:
2020/11/19-15:55:03 [25606]     Traceback (most recent call last):
2020/11/19-15:55:03 [25606]       File "/etc/munin/plugins/prosody_s2s", line 234, in <module>
2020/11/19-15:55:03 [25606]         main()
2020/11/19-15:55:03 [25606]       File "/etc/munin/plugins/prosody_s2s", line 129, in main
2020/11/19-15:55:03 [25606]         telnet = telnetlib.Telnet(host, port)
2020/11/19-15:55:03 [25606]       File "/usr/lib/python2.7/telnetlib.py", line 211, in __init__
2020/11/19-15:55:03 [25606]         self.open(host, port, timeout)
2020/11/19-15:55:03 [25606]       File "/usr/lib/python2.7/telnetlib.py", line 227, in open
2020/11/19-15:55:03 [25606]         self.sock = socket.create_connection((host, port), timeout)
2020/11/19-15:55:03 [25606]       File "/usr/lib/python2.7/socket.py", line 575, in create_connection
2020/11/19-15:55:03 [25606]         raise err
2020/11/19-15:55:03 [25606]     socket.error: [Errno 111] Connection refused
2020/11/19-15:55:03 [25606] Service 'prosody_s2s' exited with status 1/0.
2020/11/19-15:55:03 [25606] Error output from prosody_presence:
2020/11/19-15:55:03 [25606]     Traceback (most recent call last):
2020/11/19-15:55:03 [25606]       File "/etc/munin/plugins/prosody_presence", line 234, in <module>
2020/11/19-15:55:03 [25606]         main()
2020/11/19-15:55:03 [25606]       File "/etc/munin/plugins/prosody_presence", line 152, in main
2020/11/19-15:55:03 [25606]         telnet = telnetlib.Telnet(host, port)
2020/11/19-15:55:03 [25606]       File "/usr/lib/python2.7/telnetlib.py", line 211, in __init__
2020/11/19-15:55:03 [25606]         self.open(host, port, timeout)
2020/11/19-15:55:03 [25606]       File "/usr/lib/python2.7/telnetlib.py", line 227, in open
2020/11/19-15:55:03 [25606]         self.sock = socket.create_connection((host, port), timeout)
2020/11/19-15:55:03 [25606]       File "/usr/lib/python2.7/socket.py", line 575, in create_connection
2020/11/19-15:55:03 [25606]         raise err
2020/11/19-15:55:03 [25606]     socket.error: [Errno 111] Connection refused
2020/11/19-15:55:03 [25606] Service 'prosody_presence' exited with status 1/0.
2020/11/19-15:55:07 [25606] Error output from prosody_c2s:
2020/11/19-15:55:07 [25606]     Traceback (most recent call last):
2020/11/19-15:55:07 [25606]       File "/etc/munin/plugins/prosody_c2s", line 234, in <module>
2020/11/19-15:55:07 [25606]         main()
2020/11/19-15:55:07 [25606]       File "/etc/munin/plugins/prosody_c2s", line 96, in main
2020/11/19-15:55:07 [25606]         telnet = telnetlib.Telnet(host, port)
2020/11/19-15:55:07 [25606]       File "/usr/lib/python2.7/telnetlib.py", line 211, in __init__
2020/11/19-15:55:07 [25606]         self.open(host, port, timeout)
2020/11/19-15:55:07 [25606]       File "/usr/lib/python2.7/telnetlib.py", line 227, in open
2020/11/19-15:55:07 [25606]         self.sock = socket.create_connection((host, port), timeout)
2020/11/19-15:55:07 [25606]       File "/usr/lib/python2.7/socket.py", line 575, in create_connection
2020/11/19-15:55:07 [25606]         raise err
2020/11/19-15:55:07 [25606]     socket.error: [Errno 111] Connection refused
2020/11/19-15:55:07 [25606] Service 'prosody_c2s' exited with status 1/0.
2020/11/19-15:55:09 [25606] Error output from prosody_mem:
2020/11/19-15:55:09 [25606]     Traceback (most recent call last):
2020/11/19-15:55:09 [25606]       File "/etc/munin/plugins/prosody_mem", line 234, in <module>
2020/11/19-15:55:09 [25606]         main()
2020/11/19-15:55:09 [25606]       File "/etc/munin/plugins/prosody_mem", line 65, in main
2020/11/19-15:55:09 [25606]         telnet = telnetlib.Telnet(host, port)
2020/11/19-15:55:09 [25606]       File "/usr/lib/python2.7/telnetlib.py", line 211, in __init__
2020/11/19-15:55:09 [25606]         self.open(host, port, timeout)
2020/11/19-15:55:09 [25606]       File "/usr/lib/python2.7/telnetlib.py", line 227, in open
2020/11/19-15:55:09 [25606]         self.sock = socket.create_connection((host, port), timeout)
2020/11/19-15:55:09 [25606]       File "/usr/lib/python2.7/socket.py", line 575, in create_connection
2020/11/19-15:55:09 [25606]         raise err
2020/11/19-15:55:09 [25606]     socket.error: [Errno 111] Connection refused
2020/11/19-15:55:09 [25606] Service 'prosody_mem' exited with status 1/0.
2020/11/19-15:55:09 [25606] Error output from prosody_uptime:
2020/11/19-15:55:09 [25606]     Traceback (most recent call last):
2020/11/19-15:55:09 [25606]       File "/etc/munin/plugins/prosody_uptime", line 234, in <module>
2020/11/19-15:55:09 [25606]         main()
2020/11/19-15:55:09 [25606]       File "/etc/munin/plugins/prosody_uptime", line 180, in main
2020/11/19-15:55:09 [25606]         telnet = telnetlib.Telnet(host, port)
2020/11/19-15:55:09 [25606]       File "/usr/lib/python2.7/telnetlib.py", line 211, in __init__
2020/11/19-15:55:09 [25606]         self.open(host, port, timeout)
2020/11/19-15:55:09 [25606]       File "/usr/lib/python2.7/telnetlib.py", line 227, in open
2020/11/19-15:55:09 [25606]         self.sock = socket.create_connection((host, port), timeout)
2020/11/19-15:55:09 [25606]       File "/usr/lib/python2.7/socket.py", line 575, in create_connection
2020/11/19-15:55:09 [25606]         raise err
2020/11/19-15:55:09 [25606]     socket.error: [Errno 111] Connection refused
2020/11/19-15:55:09 [25606] Service 'prosody_uptime' exited with status 1/0.
2020/11/19-15:55:09 [25606] Error output from prosody_users:
2020/11/19-15:55:09 [25606]     Traceback (most recent call last):
2020/11/19-15:55:09 [25606]       File "/etc/munin/plugins/prosody_users", line 234, in <module>
2020/11/19-15:55:09 [25606]         main()
2020/11/19-15:55:09 [25606]       File "/etc/munin/plugins/prosody_users", line 196, in main
2020/11/19-15:55:09 [25606]         telnet = telnetlib.Telnet(host, port)
2020/11/19-15:55:09 [25606]       File "/usr/lib/python2.7/telnetlib.py", line 211, in __init__
2020/11/19-15:55:09 [25606]         self.open(host, port, timeout)
2020/11/19-15:55:09 [25606]       File "/usr/lib/python2.7/telnetlib.py", line 227, in open
2020/11/19-15:55:09 [25606]         self.sock = socket.create_connection((host, port), timeout)
2020/11/19-15:55:09 [25606]       File "/usr/lib/python2.7/socket.py", line 575, in create_connection
2020/11/19-15:55:09 [25606]         raise err
2020/11/19-15:55:09 [25606]     socket.error: [Errno 111] Connection refused
2020/11/19-15:55:09 [25606] Service 'prosody_users' exited with status 1/0.
2020/11/19-15:55:09 [25606] Error output from prosody_users:
2020/11/19-15:55:09 [25606]     Traceback (most recent call last):
2020/11/19-15:55:09 [25606]       File "/etc/munin/plugins/prosody_users", line 234, in <module>
2020/11/19-15:55:09 [25606]         main()
2020/11/19-15:55:09 [25606]       File "/etc/munin/plugins/prosody_users", line 196, in main
2020/11/19-15:55:09 [25606]         telnet = telnetlib.Telnet(host, port)
2020/11/19-15:55:09 [25606]       File "/usr/lib/python2.7/telnetlib.py", line 211, in __init__
2020/11/19-15:55:09 [25606]         self.open(host, port, timeout)
2020/11/19-15:55:09 [25606]       File "/usr/lib/python2.7/telnetlib.py", line 227, in open
2020/11/19-15:55:09 [25606]         self.sock = socket.create_connection((host, port), timeout)
2020/11/19-15:55:09 [25606]       File "/usr/lib/python2.7/socket.py", line 575, in create_connection
2020/11/19-15:55:09 [25606]         raise err
2020/11/19-15:55:09 [25606]     socket.error: [Errno 111] Connection refused
2020/11/19-15:55:09 [25606] Service 'prosody_users' exited with status 1/0.
```

**Comment by julian70400** [comment]
We need in prosody the admin_telnet module ! 

==> close
