### ISSUE TITLE
prosody_mem memory usage - lacking dependency info?

### ISSUE THREAD

**Issue by Bretos** [jarus/munin-prosody#8]
When updatating, getting memory usage info generates munin errors:

```
2015/05/15-18:25:04 CONNECT TCP Peer: "[10.0.0.1]:55766" Local: "[10.0.0.12]:4949"
2015/05/15-18:25:11 [18552] Error output from prosody_mem:
2015/05/15-18:25:11 [18552]     Traceback (most recent call last):
2015/05/15-18:25:11 [18552]       File "/etc/munin/plugins/prosody_mem", line 234, in <module>
2015/05/15-18:25:11 [18552]         main()
2015/05/15-18:25:11 [18552]       File "/etc/munin/plugins/prosody_mem", line 78, in main
2015/05/15-18:25:11 [18552]         print "memory_total.value", mem_map["allocated"]
2015/05/15-18:25:11 [18552]     KeyError: 'allocated'
2015/05/15-18:25:11 [18552] Service 'prosody_mem' exited with status 1/0.
```

**Comment by gllmhyt** [comment]
Quite the same here (Debian Jessie, Prosody 0.10).

```
# munin-run prosody_mem
memory_total.value
Traceback (most recent call last):
  File "/etc/munin/plugins/prosody_mem", line 234, in <module>
    main()
  File "/etc/munin/plugins/prosody_mem", line 78, in main
    print "memory_total.value", mem_map["allocated"]
KeyError: 'allocated'
```

**Comment by hoedlmoser** [comment]
same here, one of the commands used not working (any more?) with prosody 0.10

```
>for k,v in pairs(pposix.meminfo()) do print(k,v, '|') end
| Fatal error while running command, it did not complete
| Error: console:1: attempt to index global 'pposix' (a nil value)
>collectgarbage('count')*1024
| Result: 6322677

```

**Comment by hoedlmoser** [comment]
oh, pposix ist just not initialized. find patch below

```
--- prosody_.orig	2014-02-13 07:30:33.147382011 +0100
+++ prosody_	2017-02-25 14:26:23.436000000 +0100
@@ -63,7 +63,7 @@
         else:
             memstats_re = re.compile(r"\|\s(\w+)\s+(\d+)\s+\|")
             telnet = telnetlib.Telnet(host, port)
-            telnet.write(">for k,v in pairs(pposix.meminfo()) do print(k,v, '|') end\n")
+            telnet.write(">local pposix = assert(require 'util.pposix'); for k,v in pairs(pposix.meminfo()) do print(k,v, '|') end\n")
             mem_response = telnet.read_until("Result:", 5)
             telnet.write(">collectgarbage('count')*1024\n")
             telnet.write("quit\n")
```

**Comment by nioc** [comment]
Same error on Debian stretch and Prosody 0.9.12-2.
The fix proposed by @hoedlmoser does not work for me.

**Comment by lemmy04** [comment]
same here. even with the patch above I still get:
(running on openSUSE Leap 42.3)

`cloud:/etc/munin/plugins # munin-run prosody_mem
memory_total.value
Traceback (most recent call last):
  File "/etc/munin/plugins/prosody_mem", line 234, in <module>
    main()
  File "/etc/munin/plugins/prosody_mem", line 78, in main
    print "memory_total.value", mem_map["allocated"]
KeyError: 'allocated'`

**Comment by t2d** [comment]
https://github.com/jarus/munin-prosody/issues/8#issuecomment-282483976 works with Debian stretch and prosody 0.11.0
